name: app.js CI/CD Pipeline

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define jobs for the workflow
jobs:
  build:

    # The type of machine to run on
    runs-on: ubuntu-latest

    # Steps to perform
    steps:
    # Checkout the repository to the runner
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Node.js version
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # You can adjust the Node version according to your project

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # # Run tests (ensure that your project has a test script defined in package.json)
    # - name: Run tests
    #   run: npm test

    # Linting (optional: if you use a linter like ESLint in your project)
    - name: Lint code
      run: npm run lint

    # Build the project (if applicable)
    - name: Build the project
      run: npm run build
